[package]
name = "autogit"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "An interactive CLI tool to automate operations on GitHub using its API"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
tabled = "0.8.0"
colored = "2.0.0"
